// Stamps the current UTC build time into src/build-info.js (gitignored).
// Run automatically by the "build" npm script before Parcel bundles, so the
// editor footer always reflects the bundle you are actually loading.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const date = new Date().toISOString().slice(0, 16) + 'Z'; // YYYY-MM-DDTHH:mmZ
const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'build-info.js');

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen_build_info.mjs at build time. Do not edit or commit.\n` +
    `export const BUILD_DATE = ${JSON.stringify(date)};\n`,
);

console.log('build-info.js ->', date);
